### ISSUE TITLE
Ctrl-a and Ctrl-e in forward/reverse search

### ISSUE THREAD

**Issue by ViralBShah** [Keno/REPL.jl#16] opened 2014-01-12 19:46 UTC
I commonly do `Ctrl-r` to search in the history, and when I find the right match, `Ctrl-a` / `Ctrl-e` to navigate to the beginning/end of the line. This does not quite work as it does in the current repl.

**Comment by ivarne** [comment] 2014-01-12 20:14
This looks like a dup of https://github.com/loladiro/REPL.jl/issues/16

**Comment by Keno** [comment] 2014-01-12 20:17
I think you mean #12. @ViralBShah, can you see if this is fixed.

**Comment by ivarne** [comment] 2014-01-12 20:30
You are right. I copied the wrong url when I had both issues open in different tabs. Good thing I did not link some random issue.

**Comment by carlobaldassi** [comment] 2014-01-12 20:46
Nope, it's not a duplicate, since even if #12 is fixed, those key bindings still cause issues when the current search result is being displayed.
Also, it becomes really messy when dealing with multi-line inputs.

**Comment by carlobaldassi** [comment] 2014-01-12 20:51
Also, I occasionally get this error while experimenting with reverse search:

```
ERROR: BoundsError()
 in rsearch at string.jl:1604
 in rsearch at ascii.jl:21
 in rsearchindex at string.jl:436
 in rsearch at string.jl:452
 in history_search at /home/carlo/.julia/REPL/src/REPL.jl:250
 in update_display_buffer at /home/carlo/.julia/Readline/src/Readline.jl:698
 in keymap_func at /home/carlo/.julia/Readline/src/Readline.jl:652
 in prompt! at /home/carlo/.julia/Readline/src/Readline.jl:957
 in run_interface at /home/carlo/.julia/Readline/src/Readline.jl:939
 in run_repl at /home/carlo/.julia/REPL/src/REPL.jl:478
 in anonymous at no file:32
 in include_from_node1 at loading.jl:120
while loading /home/carlo/.julia/REPL/scripts/repl.jl, in expression starting on line 7
```

but so far my attempts at finding a reproducible sequence of keys which triggers this has failed. Will try some more.

**Comment by Keno** [comment] 2014-01-14 04:08
I fixed the multiline ^A, ^E thing, but I don't quite understand what this issue is about.

**Comment by carlobaldassi** [comment] 2014-01-14 15:26
This issue can be reproduced as follows (at least on my PC):
1. at the REPL, press ctrl+r to initiate the search: this brings up the `(reverse-i-search)`':` prompt.
2. type something (e.g. `for`) and a candidate entry from the history is displayed
3. without pressing enter, and therefore while the search prompt is still being displayed, press ctrl+a, or the home key or some other control sequence

Expected behaviour based on the GNU readline repl: the search prompt is replaced with the julia prompt and a movement command is executed (e.g. ctrl+a brings you to the beginning of the line)

Actual behaviour: the control sequence becomes part of the search string, e.g. the home key is displayed as an `H`, ctrl+a is displayed as a strange (unprintable unicode) character etc.

In general, if the goal is to exactly replicate the original repl, this is how it should work: any control character, and most notably movement commands (arrows, home/end keys, ctrl+a, ctrl+e etc.), plus the enter key, bring the standard prompt back and are immediately executed.
In REPL.jl at the moment you need to first press enter to get out of the search prompt, and then use the movement commands.

I'm not claiming that the original behaviour is the right one, and it is even annoying at times, just noting the difference. Still, if I had a vote, I'd go for replicating the original behaviour exactly, to not confuse users and because of muscle memory and all that. In any case, even if movement commands are not executed until enter is pressed and the julia prompt is back, they still should not produce garbage in the search string as they do now.

**Comment by ViralBShah** [comment] 2014-01-15 02:43
@carlobaldassi Thanks for the detailed explanation. We do not need to replicate the original behaviour necessarily, but it is something I have got used to. At least the crash is fixed, which is most important here.

**Comment by Keno** [comment] 2014-01-16 00:49
Fixed in Readline.

**Closed as completed by Keno** 2014-01-16 00:49 UTC
